#ifndef OPTICAL_FLOW_CONSTANTS_H
#define OPTICAL_FLOW_CONSTANTS_H

#define DEFAULT_SEARCH_SIZE 6
#define DEFAULT_FLOW_FEATURE_THRESHOLD 30
#define DEFAULT_FLOW_VALUE_THRESHOLD 3000
#define DEFAULT_NUMBER_OF_FEATURES 20
#define DEFAULT_CONFIDENCE_MULTIPLIER 1.645f //90% confidence interval
#define DEFAULT_OUTPUT_RATE 15
#define DEFAULT_IMAGE_WIDTH 128
#define DEFAULT_IMAGE_HEIGHT 128
#define TILE_SIZE	8	// x & y tile size
#define NUM_BLOCKS 5 // x & y number of tiles to check

#endif